export const AUFGABE_HINZUFUEGEN = 'AUFGABE_HINZUFUEGEN';
export const LOESCHE_EINTRAG = 'LOESCHE_EINTRAG';
export const AUFGABEN_LADEN = 'AUFGABEN_LADEN';
export const NUMMERTRIVIA_HOLEN = 'NUMMERTRIVIA_HOLEN';
export const NUMMERTRIVIA_FEHLER = 'NUMMERTRIVIA_FEHLER';
export const FETCH_TASKLIST = 'FETCH_TASKLIST';
export const ERLEDIGT_SETZEN = 'RLEDIGT_SETZEN';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const SET_MESSAGE = 'SET_MESSAGE';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';