export const AUFGABE_HINZUFUEGEN = 'AUFGABE_HINZUFUEGEN';
export const LOESCHE_EINTRAG = 'LOESCHE_EINTRAG';
export const AUFGABEN_LADEN = 'AUFGABEN_LADEN';
export const NUMMERTRIVIA_HOLEN = 'NUMMERTRIVIA_HOLEN';
export const NUMMERTRIVIA_FEHLER = 'NUMMERTRIVIA_FEHLER';